sudo: required
services
  - docker
before_install:
  - openssl aes-256-cbc -K $encrypted_8c393341f536_key -iv $encrypted_8c393341f536_iv -in service-account.json.enc -out service-account
.json -d
  - curl https://sdk.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  # install & update kubernetes inside travis envirounment
  - gcloud components update kubectl
  # Authorization
  - gcloud auth activate-service-account --key-file service-account.json
  