apiVersion: apps/v1
kind: Deployment
metadata: 
  name: server-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
        - name: server
          image: vitkoczi/multi-server
          ports: 
          - containerPort: 5000
          # see envirounmentVar.png
          env:
            - name: REDIS_HOST
              value: redis-cluster-ip-service
            - name: REDIS_PORT
              value: "6379"
            - name: PGUSER
              value: postgres
              # name of the ip service that managing acces to the postgres pod see: postgres-cluster-ip-service.yaml
            - name: PGHOST
              value: postgres-cluster-ip-service
            - name: PGPORT
              value: "5432"
            - name: PGDATABASE
              value: postgres
              # name of the variable requested by postgres
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgpassword
                  #name of the key in the secret
                  key: PGPASSWORD
            
# do not write password in plain text
# kubectl create secret generic pgpassword --from-literal PGPASSWORD=123asdf