apiVersion: apps/v1
kind: Deployment
metadata: 
  name: worker-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: worker
  template:
    metadata:
      labels:
        component: worker
    spec:
      containers:
        - name: worker
          image: vitkoczi/multi-worker
#         ports: no ports required as noone connects to it
          env:
          #name of the cluster ip service that the worker needs to connect to, to get the reddis pod
            - name: REDIS_HOST
              # see server-cluster-ip-service.yaml
              value: redis-cluster-ip-service
            - name: REDIS_PORT
              value: '6379'
              